spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # Automatically creates tables in your TiDB database on deployment
      ddl-auto: update
    show-sql: false # Turn off in production (Render) to keep logs clean
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  # Cryptographically secure HMAC SHA-256 Key injected from Render
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 Hours